export class Bimestre {
  apellidosNombres = '';
  autoevaluacionDecir = 0;
  autoevaluacionSer = 0;
  bimestre = '';
  decirPromedio = 0;
  hacerPromedio = 0;
  idDocente: number;
  idEstudiante: number;
  idMateria: number;
  indicadorCualitativo = '';
  notaBimestralFinal = 0;
  notaDecir1 = 0;
  notaDecir2 = 0;
  notaDecir3 = 0;
  notaDecir4 = 0;
  notaDecir5 = 0;
  notaDecir6 = 0;
  notaHacer1 = 0;
  notaHacer2 = 0;
  notaHacer3 = 0;
  notaHacer4 = 0;
  notaHacer5 = 0;
  notaHacer6 = 0;
  notaSaber1 = 0;
  notaSaber2 = 0;
  notaSaber3 = 0;
  notaSaber4 = 0;
  notaSaber5 = 0;
  notaSaber6 = 0;
  notaSer1 = 0;
  notaSer2 = 0;
  notaSer3 = 0;
  notaSer4 = 0;
  notaSer5 = 0;
  notaSer6 = 0;
  observacion = '';
  promedioAutoevaluacion = 0;
  saberPromedio = 0;
  serPromedio = 0;
}
